albumFotos/urls.py
from django.contrib import admin
from django.urls import path
from fotos import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('album/', views.base, name='base'),
    path('admin/', admin.site.urls),
    path('album/category/', login_required(views.CategoryListView.as_view()), name='category-list'),
    path('album/category/<int:pk>/detail', login_required(views.CategoryDetailView.as_view()), name='category-detail'),
    path('album/photo/', login_required(views.PhotoListView.as_view()), name='photo-list'),
    path('album/photo/<int:pk>/detail', login_required(views.PhotoDetailView.as_view()), name='photo-detail'),
    #update
    path('album/photo/<int:pk>/update/', login_required(views.PhotoUpdate.as_view()), name='photo-update'),
    #create
    path('album/photo/create/', login_required(views.PhotoCreate.as_view()), name='photo-create'),
    #delete
    path('album/photo/<int:pk>/delete/', login_required(views.PhotoDelete.as_view()), name='photo-delete'),
    #login
    path('album/login', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    #logout
    path('album/logout', auth_views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'),
    #profile
    path('album/profile/<int:pk>', login_required(views.Profile.as_view(template_name='auth/profile.html')), name='profile'),
    #pwdchange
    path(
        'album/change-password/',
        login_required(auth_views.PasswordChangeView.as_view(template_name='auth/change-password.html')),
        name='password-change'
    ),
]

fotos/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    """ Categoria para clasificar las fotos """
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Photo(models.Model):
    """ Fotos del album """

    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True, blank=True)
    title = models.CharField(max_length=50, default='No Title')
    photo = models.ImageField(upload_to='photos/')
    pub_date = models.DateField(auto_now_add=True)
    favorite = models.BooleanField(default=False)
    comment = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo-list')

@receiver(post_delete, sender=Photo)
def photo_delete(sender, instance, **kwargs):
    """ Borra todos los ficheros de las fotos que se eliminan """
    instance.photo.delete(False)

fotos/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from fotos.models import Category, Photo
from django.contrib.auth.models import User

# Create your views here.
class CategoryListView(ListView):
    model = Category

class CategoryDetailView(DetailView):
    model = Category

class PhotoListView(ListView):
    model = Photo

class PhotoDetailView(DetailView):
    model = Photo

class PhotoUpdate(UpdateView):
    model = Photo
    fields = '__all__'

class PhotoCreate(CreateView):
    model = Photo
    fields = '__all__'

class PhotoDelete(DeleteView):
    model = Photo
    success_url = reverse_lazy('photo-list')

class Profile(DetailView):
    model = User

def base(request):
    return render(request, 'base.html')

fotos/templates/base.html
<!DOCTYPE html>
<html>
<head lang="es_CO">
    <meta charset="UTF-8">
    <title>Album</title>
    <!-- CDN Bootstrap -->
    <link rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css
">
    <script
src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script
src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- NavBar -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
        
            <div class="navbar-header">
                <button type="button"class="navbar-toggle collapsed"
data-toggle="collapse"data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"href="{% url 'base' %}">Album</a>
            </div> 
            <div class="collapse navbar-collapse"
id="bs-example-navbar-collapse-1">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'category-list' %}">Categorias<span class="sr-only">(current)</span></a></li>
                    <li><a href="{% url 'photo-list' %}">Fotos</a></li>
                </ul>
                {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#"class="dropdown-toggle"
data-toggle="dropdown"role="button"aria-expanded="false">Menú
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu"role="menu">
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'photo-create' %}">Subir Foto</a></li>
                                <li><a href="{% url 'profile' user.id %}">Perfil</a></li>    
                                <li class="divider"></li>
                                <li><a href="{% url 'password-change' %}">Cambiar contraseña</a></li>    
                                <li><a href="{% url 'logout' %}">Cerrar Sesión</a></li>    
                            {% else %}
                                <li><a href="{% url 'login' %}">Iniciar Sesión</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block section %}
        {% endblock section %}
    </div>
    <div class="container">
        {% block maincontent %}
            {% if user.is_authenticated %}
                <center>
                    <h1>Bienvenido a la aplicación de AlbumFotos</h1>
                    <br><br>
                    <h2>{{user.username}}</h2>
                </center>    
            {% else %}
                <center>
                    <h1>Bienvenido a la aplicación de AlbumFotos</h1>
                    <br><br>
                    <h2>Inicia Sesión para continuar...</h2>
                </center>
            {% endif %}
        {% endblock maincontent %}
    </div>
</body>
</html>

fotos/templates/fotos/category_detail.html
{% extends 'base.html' %}
{% load static %}

{% block section %}
    <h2>{{object.name}}</h2>
    <hr>
{% endblock section %}    

{% block maincontent %}
    <div>
        <table border="1px">
            <tr>
                {% for p in object.photo_set.all %}
                    <td>
                        <div>{{p.title}}</div>
                        <div>
                            <a href="{% url 'photo-detail' p.id %}">
                                <img src="{% static p.photo.url %}"
    style="width:200px;height:200px"/>
                            </a>
                        </div>
                    </td>
                {% endfor %}
            </tr>
        </table>
    </div>
{% endblock maincontent %}

fotos/templates/fotos/category_list.html
{% extends 'base.html' %}

{% block section %}
    <h2>Category</h2>
    <hr>
{% endblock section %}    

{% block maincontent %}
    <div>
        <ul>
            {% for s in object_list %}
                    <li>
                    <a href="{% url 'category-detail' s.id %}" >
                        {{ s.name }}
                    </a>
                    </li>
            {% endfor %}
        </ul>
    </div>
{% endblock maincontent %}

fotos/templates/fotos/photo_confirm_delete.html
{% extends 'base.html' %}

{% block maincontent %}
    <form action="" method="post">{% csrf_token %}
    <p>Delete "{{ object.title }}"?</p>
    <input type="submit" value="Confirm" />
    <a class='btn' href="{% url 'photo-list' %}">Cancel</a>
    </form>
{% endblock maincontent %}

fotos/templates/fotos/photo_detail.html
{% extends 'base.html' %}
{% load static %}

{% block section %}
    <h2>
        {{ object.title }}
        {% if object.favorite %}
            &#9733;
        {% else %}
            &#9734;
        {% endif %}
        {% if object.category_id %}
        ( <a href="{% url "category-detail" object.category_id %}">{{object.category }}</a>)
        {% endif %}   
    </h2>
    <p><strong>comments:</strong>{{ object.comment|default:"no comments" }}</p>
    <a href="{% url "photo-update" object.id %}">edit</a>
    <a href="{% url "photo-delete" object.id %}">delete</a>
    <hr>
{% endblock section %}

{% block maincontent %}
<div>
    <div>
        <img src="{% static object.photo.url %}"
style = "width:550px;height:420px"/>
    </div>
</div>
{% endblock maincontent %}

fotos/templates/fotos/photo_form.html
{% extends "base.html" %}

{% block maincontent %}
    <form enctype="multipart/form-data" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
        <a class='btn' href="{% url 'photo-list' %}">Cancel</a>
    </form>
{% endblock maincontent%}

fotos/templates/fotos/photo_list.html
{% extends 'base.html' %}

{% load static %}

{% block section %}
    <h2>Photo</h2>
    <hr>
{% endblock section %}

{% block maincontent %}
    <div class="row well">
        {% for p in object_list.all %}
            <div class="col-md-4 well">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ p.title }}</h3>
                    </div>
                    <div class="panel-body">
                        <a href="{% url "photo-detail" p.id %}">
                            <img src="{% static p.photo.url %}"style="width:200px;height:200px;"/>
                        </a>
                    </div>
                    <div class="panel-footer">
                        {% if p.comment %}
                            {{ p.comment }}
                        {% else %}
                            <a href="{% url "photo-update" p.id %}">edit comments</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock maincontent %} 